name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.23"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5.1.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache-dependency-path: go.sum
      - name: Display Go version
        run: go version
      - name: Lint
        run: make lint
      - name: Test
        run: make test
